/* AURORA Data IO + Knowledge Explorer + model lifecycle bridge. */
(() => {
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  function mountIO(){const view=document.getElementById('aurora-view-io');if(!view||document.getElementById('aurora-io-overview'))return;const p=document.createElement('section');p.id='aurora-io-overview';p.className='card';p.innerHTML='<h2>Data IO pipeline</h2><p class="muted">AURORA treats imported material as evidence-bearing input and exported cognitive state as portable state. Derived indexes can be rebuilt.</p><div class="aurora-grid"><div class="aurora-stat"><span>1 · Ingest</span><b>Source</b></div><div class="aurora-stat"><span>2 · Process</span><b>Parse / chunk</b></div><div class="aurora-stat"><span>3 · Cognition</span><b>Claims / evidence</b></div><div class="aurora-stat"><span>4 · Preserve</span><b>Export / restore</b></div></div>';view.insertBefore(p,view.children[1]||null);}
  async function searchKnowledge(){const q=document.getElementById('aurora-knowledge-query')?.value.trim()||'',kind=document.getElementById('aurora-knowledge-kind')?.value||'all',out=document.getElementById('aurora-knowledge-results'),ws=document.getElementById('workspace')?.value.trim();if(!out)return;if(!ws){out.innerHTML='<div class="aurora-empty">Select a workspace first.</div>';return;}out.textContent='Searching knowledge…';try{const token=document.getElementById('token')?.value.trim();const r=await fetch(`/v1/knowledge/search?workspace_id=${encodeURIComponent(ws)}&q=${encodeURIComponent(q)}&kind=${encodeURIComponent(kind)}&limit=50`,{headers:{Authorization:`Bearer ${token}`}});const d=await r.json();if(!r.ok)throw new Error(d.detail||r.statusText);out.innerHTML=d.length?d.map(x=>`<article class="knowledge-result item"><div class="row"><span class="badge">${esc(x.type)}</span>${x.status?`<span class="badge">${esc(x.status)}</span>`:''}</div><button type="button" class="knowledge-open" data-id="${esc(x.id)}" data-type="${esc(x.type)}"><strong>${esc(x.title)}</strong></button>${x.confidence!=null?`<div class="knowledge-meta">Confidence ${Number(x.confidence).toFixed(2)}</div>`:''}${x.excerpt?`<p>${esc(x.excerpt)}</p>`:''}</article>`).join(''):'<div class="aurora-empty">No matching claims or documents.</div>';out.querySelectorAll('.knowledge-open').forEach(b=>b.onclick=()=>{if(b.dataset.type==='claim'){const p=document.getElementById('aurora-provenance-claim');if(p){p.value=b.dataset.id;document.getElementById('aurora-provenance-load')?.click();}location.hash='provenance';}else{const q=document.getElementById('aurora-knowledge-query');if(q)q.value=b.textContent.trim();}});}catch(e){out.innerHTML=`<div class="aurora-empty">Knowledge search failed: ${esc(e.message)}</div>`;}}
  function mountKnowledge(){const view=document.getElementById('aurora-view-knowledge');if(!view||document.getElementById('aurora-knowledge-panel'))return;const p=document.createElement('section');p.id='aurora-knowledge-panel';p.className='card';p.innerHTML='<h2>Knowledge Explorer</h2><p class="muted">Search persisted claims and documents. Claims remain explicitly uncertain until reviewed.</p><div class="knowledge-toolbar row"><input id="aurora-knowledge-query" placeholder="Search claims, evidence excerpts or document titles"><select id="aurora-knowledge-kind"><option value="all">Claims + documents</option><option value="claims">Claims only</option><option value="documents">Documents only</option></select><button id="aurora-knowledge-search" type="button">Search</button></div><div id="aurora-knowledge-results"><div class="aurora-empty">Search the active workspace.</div></div>';view.appendChild(p);document.getElementById('aurora-knowledge-search').onclick=searchKnowledge;document.getElementById('aurora-knowledge-query').addEventListener('keydown',e=>{if(e.key==='Enter')searchKnowledge();});}
  function bridge(){mountIO();mountKnowledge();window.AuroraModelAccess?.mount?.();}
  window.AuroraDataIO={mount:mountIO};window.AuroraKnowledge={mount:mountKnowledge,search:searchKnowledge};
  document.addEventListener('DOMContentLoaded',()=>{const observer=new MutationObserver(()=>{bridge();if(document.getElementById('aurora-view-io')&&document.getElementById('aurora-view-knowledge')&&document.getElementById('aurora-model-access'))observer.disconnect();});observer.observe(document.body,{childList:true,subtree:true});bridge();});
})();
