/* AURORA Figma UI v2 bridge — visual layer only. Preserves existing MVP API/DOM contracts. */
(() => {
  const apply = () => {
    const shell = document.querySelector('.aurora-shell');
    if (!shell) return setTimeout(apply, 40);
    const style = document.createElement('style');
    style.id = 'aurora-figma-v2-style';
    style.textContent = `
      :root{--aurora-bg:#06080c;--aurora-panel:#0c1118;--aurora-panel2:#101720;--aurora-line:rgba(255,255,255,.09);--aurora-line2:rgba(255,255,255,.14);--aurora-text:#f4f7fa;--aurora-muted:#8995a3;--aurora-soft:#c9d3dc;--aurora-accent:#dce9f4;--aurora-good:#72d6a1;--aurora-warn:#f1c77a}
      html,body{background:var(--aurora-bg)!important;color:var(--aurora-text)!important}
      .aurora-shell{grid-template-columns:236px minmax(0,1fr)!important;background:radial-gradient(900px 420px at 65% -10%,rgba(100,140,180,.10),transparent 65%),var(--aurora-bg)}
      .aurora-rail{background:rgba(7,10,14,.94)!important;border-right:1px solid var(--aurora-line)!important;padding:20px 14px!important}
      .aurora-brand{font-size:19px!important;letter-spacing:.16em!important}.aurora-sub{color:#687482!important;padding-bottom:24px!important}.aurora-nav{gap:5px!important}
      .aurora-nav button{border:1px solid transparent!important;border-radius:9px!important;padding:11px 12px!important;color:#8f9ba8!important}.aurora-nav button:hover{background:rgba(255,255,255,.045)!important;color:#e9eef3!important}.aurora-nav button.active{background:rgba(255,255,255,.075)!important;border-color:var(--aurora-line)!important;color:#fff!important}
      .aurora-top{height:70px!important;background:rgba(8,12,17,.86)!important;backdrop-filter:blur(18px)!important;border-bottom:1px solid var(--aurora-line)!important;padding:0 28px!important}.aurora-context strong{font-size:12px!important;letter-spacing:.12em!important}.aurora-context span{color:#65717e!important}.aurora-askbar{max-width:560px!important}.aurora-askbar input{height:40px!important;border-radius:10px!important;background:rgba(255,255,255,.035)!important;border-color:var(--aurora-line)!important}.aurora-askbar button{height:40px!important;border-radius:10px!important;padding:0 17px!important}
      .aurora-main{max-width:1480px!important;padding:30px 34px 50px!important}.aurora-hero{margin-bottom:24px!important}.aurora-kicker{font-size:10px!important;letter-spacing:.18em!important;color:#8298aa!important}.aurora-hero h1{font-size:30px!important;letter-spacing:-.025em!important;margin:6px 0!important}.aurora-hero p{font-size:13px!important;color:#7f8c9a!important}.aurora-grid{gap:12px!important;margin:18px 0!important}
      .aurora-stat,.aurora-next,.card,.aurora-layer{background:linear-gradient(180deg,rgba(255,255,255,.035),rgba(255,255,255,.018))!important;border:1px solid var(--aurora-line)!important;border-radius:12px!important;box-shadow:0 12px 35px rgba(0,0,0,.10)!important}.aurora-stat{padding:16px!important}.aurora-stat b{font-size:21px!important}.card{padding:18px!important}.card h2{font-size:14px!important;letter-spacing:.01em!important}
      input,textarea,select{background:#090e14!important;border-color:var(--aurora-line2)!important;color:var(--aurora-text)!important}input:focus,textarea:focus,select:focus{outline:none!important;border-color:rgba(220,233,244,.38)!important;box-shadow:0 0 0 3px rgba(220,233,244,.06)!important}button{border-radius:9px!important}.metric,.badge{background:rgba(255,255,255,.055)!important;border:1px solid var(--aurora-line)!important}.aurora-empty{background:rgba(255,255,255,.018)!important}.aurora-statusbar{background:#090d13!important;border-bottom:1px solid var(--aurora-line)!important}.aurora-statusbar .conn-good{color:var(--aurora-good)!important}.aurora-statusbar .conn-neutral{color:#8a96a4!important}
      .aurora-figma-transparency{margin-top:14px;border:1px solid var(--aurora-line);border-radius:12px;background:rgba(255,255,255,.022);overflow:hidden}.aurora-figma-transparency header{display:flex;justify-content:space-between;align-items:center;padding:13px 15px;border-bottom:1px solid var(--aurora-line)}.aurora-figma-transparency header strong{font-size:11px;letter-spacing:.14em;text-transform:uppercase}.aurora-figma-transparency .tf-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px;padding:12px}.aurora-figma-transparency .tf-card{padding:13px;border:1px solid var(--aurora-line);border-radius:9px;background:rgba(0,0,0,.12)}.aurora-figma-transparency .tf-label{font-size:10px;text-transform:uppercase;letter-spacing:.12em;color:#687583}.aurora-figma-transparency .tf-value{margin-top:5px;font-size:15px;font-weight:650}.aurora-figma-transparency .tf-value.good{color:var(--aurora-good)}.aurora-figma-transparency .tf-value.warn{color:var(--aurora-warn)}
      .aurora-mobile-menu{display:none;align-items:center;justify-content:center;width:36px;height:36px;border:1px solid var(--aurora-line);background:rgba(255,255,255,.04);color:#fff;border-radius:9px;margin-right:10px}.aurora-mobile-overlay{display:none}
      @media(max-width:900px){.aurora-shell{grid-template-columns:1fr!important}.aurora-rail{position:fixed!important;left:0;top:0;bottom:0;width:270px!important;z-index:1000;transform:translateX(-102%);transition:transform .18s ease;border-right:1px solid var(--aurora-line)!important}.aurora-rail.mobile-open{transform:translateX(0)}.aurora-top{padding:0 16px!important}.aurora-main{padding:22px 16px 40px!important}.aurora-mobile-menu{display:inline-flex!important}.aurora-mobile-overlay{position:fixed;inset:0;background:rgba(0,0,0,.58);z-index:999}.aurora-mobile-overlay.open{display:block}}
      @media(max-width:600px){.aurora-top{height:62px!important}.aurora-main{padding:18px 11px 30px!important}.aurora-hero h1{font-size:25px!important}.aurora-grid{grid-template-columns:1fr 1fr!important}.aurora-figma-transparency .tf-grid{grid-template-columns:1fr!important}.aurora-askbar{display:none!important}}
    `;
    document.head.appendChild(style);
    const top=document.querySelector('.aurora-top'),rail=document.querySelector('.aurora-rail');
    if(top&&rail&&!document.querySelector('.aurora-mobile-menu')){const menu=document.createElement('button');menu.className='aurora-mobile-menu';menu.type='button';menu.setAttribute('aria-label','Open navigation');menu.textContent='☰';const overlay=document.createElement('div');overlay.className='aurora-mobile-overlay';document.body.appendChild(overlay);top.prepend(menu);const close=()=>{rail.classList.remove('mobile-open');overlay.classList.remove('open')};menu.onclick=()=>{rail.classList.add('mobile-open');overlay.classList.add('open')};overlay.onclick=close;rail.querySelectorAll('button').forEach(b=>b.addEventListener('click',close))}
    const answer=document.getElementById('answer'),think=answer?.closest('.aurora-view');
    if(answer&&think&&!document.getElementById('aurora-fact-panel')){const panel=document.createElement('section');panel.id='aurora-fact-panel';panel.className='aurora-figma-transparency';panel.innerHTML='<header><strong>Transparency</strong><span class="muted">Evidence · confidence · provenance</span></header><div class="tf-grid"><div class="tf-card"><div class="tf-label">Confidence</div><div id="tf-confidence" class="tf-value">Not scored</div></div><div class="tf-card"><div class="tf-label">Evidence</div><div id="tf-evidence" class="tf-value">0 items</div></div><div class="tf-card"><div class="tf-label">Claims</div><div id="tf-claims" class="tf-value">Inspect in Knowledge</div></div><div class="tf-card"><div class="tf-label">Reasoning</div><div id="tf-reasoning" class="tf-value">Waiting</div></div></div>';answer.parentElement?.appendChild(panel);const refresh=()=>{const txt=answer.textContent?.trim()||'',ev=document.querySelectorAll('#evidence article').length,claims=document.getElementById('claims')?.textContent||'',conf=(window.auroraLastAnswer&&window.auroraLastAnswer.confidence!=null)?Math.round(Number(window.auroraLastAnswer.confidence)*100)+'%':'Not scored';const c=document.getElementById('tf-confidence');c.textContent=conf;c.className='tf-value '+(conf==='Not scored'?'':'good');document.getElementById('tf-evidence').textContent=`${ev} item${ev===1?'':'s'}`;document.getElementById('tf-claims').textContent=claims.includes('No competing')?'No open conflicts':'Review in Knowledge';document.getElementById('tf-reasoning').textContent=txt&&!txt.startsWith('No reasoning')?'Completed':'Waiting'};setInterval(refresh,800)}
  }; document.addEventListener('DOMContentLoaded',apply);
})();
