/* AURORA Profile: identity, authentication and per-user provider configuration. */
(() => {
  const $ = id => document.getElementById(id);
  const esc = value => String(value ?? '').replace(/[&<>\"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
  const TEST_EMAIL = 'test@aurora.app';
  let profileView, navButton, signInGate;
  const signedIn = () => typeof window.token === 'function' && !!window.token();
  const goProfile = () => navButton?.click();
  function hideGate(){ if(signInGate) signInGate.style.display='none'; }
  function showGate(){
    if(signedIn()){hideGate();return;}
    if(signInGate){signInGate.style.display='flex';return;}
    signInGate=document.createElement('div'); signInGate.id='aurora-signin-gate';
    signInGate.innerHTML='<div class="aurora-auth-card"><div class="aurora-kicker">AURORA / AUTHENTICATION</div><h1>Sign in to AURORA</h1><p class="muted">AURORA requires an authenticated identity before the cognitive workspace can be used.</p><label>Email</label><input id="gateEmail" type="email" autocomplete="username"><label>Password</label><input id="gatePassword" type="password" autocomplete="current-password"><div class="row"><button id="gateSignIn">Sign in</button><button id="gateCreate" class="secondary">Create profile</button></div><div id="gateStatus" class="status muted"></div><div class="aurora-test-note"><b>MVP test account</b><br>test@aurora.app<br>Credentials are pre-populated for local MVP testing.</div></div>';
    document.body.appendChild(signInGate);
    $('gateEmail').value=TEST_EMAIL; $('gatePassword').value=$('password')?.value||'';
    $('gateSignIn').onclick=async()=>{ $('email').value=$('gateEmail').value; $('password').value=$('gatePassword').value; await window.signIn(); if(signedIn()){hideGate();await refreshProfile();await window.loadWorkspaces?.();} else $('gateStatus').textContent=$('authStatus')?.textContent||'Sign-in failed.'; };
    $('gateCreate').onclick=()=>{hideGate();goProfile();setTimeout(()=>$('profile-create-email')?.focus(),50);};
  }
  async function signup(email,password){
    const base=$('supabaseUrl').value.trim().replace(/\/$/,''); const key=$('publishableKey').value.trim();
    const r=await fetch(`${base}/auth/v1/signup`,{method:'POST',headers:{'Content-Type':'application/json',apikey:key},body:JSON.stringify({email,password})});
    const d=await r.json(); if(!r.ok)throw new Error(d.msg||d.message||d.error_description||'Profile creation failed'); return d;
  }
  async function refreshProfile(){
    if(!signedIn())return;
    try{const d=await window.api('/v1/profile');const p=d.profile||{};$('profileDisplayName').value=p.display_name||'';$('profileTimezone').value=p.timezone||'';$('profileDefaultModel').value=p.default_model||'';$('profileCredentialStatus').innerHTML=`<div><b>OpenRouter:</b> ${d.openrouter?.configured?'configured via AURORA server environment':'not configured'}</div><div><b>Puter:</b> ${d.credentials?.some(x=>x.provider==='puter')?'configured':'browser account — connect when needed'}</div>`;$('profileIdentity').innerHTML=`<b>Signed in</b><br>${esc(d.user_id)}<br><span class="muted">Provider secrets are never returned in plaintext.</span>`;}catch(e){$('profileStatus').textContent=`Profile load failed: ${e.message}`;}
  }
  async function saveProfile(){try{await window.api('/v1/profile',{method:'PATCH',body:JSON.stringify({display_name:$('profileDisplayName').value.trim()||null,timezone:$('profileTimezone').value.trim()||null,default_model:$('profileDefaultModel').value.trim()||null,preferences:{}})});$('profileStatus').textContent='Profile saved.';}catch(e){$('profileStatus').textContent=e.message;}}
  async function saveCredential(provider,label,secret){try{const d=await window.api('/v1/profile/credentials',{method:'PUT',body:JSON.stringify({provider,label,secret:secret||null,metadata:{}})});$('profileStatus').textContent=`${provider} credential ${d.configured?'saved securely.':'unchanged.'}`;await refreshProfile();}catch(e){$('profileStatus').textContent=`Credential save failed: ${e.message}`;}}
  function createProfileView(){
    const main=document.querySelector('.aurora-main');if(!main)return;
    profileView=document.createElement('div');profileView.className='aurora-view';profileView.dataset.view='profile';profileView.id='aurora-view-profile';profileView.innerHTML=`<div class="aurora-hero"><div class="aurora-kicker">AURORA / PROFILE</div><h1>Profile</h1><p>Manage identity, authentication and user-specific provider configuration.</p></div><section class="card"><h2>Identity</h2><div id="profileIdentity" class="muted">Not signed in.</div><div class="grid"><div><label>Display name</label><input id="profileDisplayName" placeholder="Your name"><label>Timezone</label><input id="profileTimezone" placeholder="Pacific/Auckland"><label>Default model</label><input id="profileDefaultModel" placeholder="Optional model identifier"><button id="profileSave">Save profile</button></div><div><h3>Account</h3><div class="row"><button id="profileSignIn">Sign in</button><button id="profileSignOut" class="secondary">Log out</button></div><div id="profileStatus" class="status muted"></div></div></div></section><section class="card"><h2>Provider & execution credentials</h2><p class="muted">Secrets go only to the authenticated AURORA backend and are stored using Supabase Vault. They are never written to browser local storage or returned to the UI.</p><div class="item"><h3>OpenRouter</h3><div id="profileCredentialStatus" class="muted">Checking configuration…</div><p class="muted">The MVP test account uses the server-side <code>OPENROUTER_API_KEY</code> configured in the AURORA server environment. The key itself is never exposed to the browser.</p><label>Optional user-specific OpenRouter key</label><input id="profileOpenRouterKey" type="password" autocomplete="new-password" placeholder="sk-or-…"><button id="profileSaveOpenRouter">Save OpenRouter key</button></div><div class="item"><h3>Puter</h3><p class="muted">Puter.js authentication is browser-based. AURORA does not need or store your Puter login secret.</p><button id="profileConnectPuter">Connect Puter account</button><div id="profilePuterStatus" class="status muted">Not connected.</div></div><div class="item"><h3>Additional providers</h3><p class="muted">The credential vault is extensible for OpenAI, Anthropic, Google and future providers.</p></div></section><section class="card"><h2>Create profile</h2><p class="muted">Create a new Supabase identity. Email confirmation may be required.</p><label>Email</label><input id="profile-create-email" type="email" placeholder="you@example.com"><label>Password</label><input id="profile-create-password" type="password" autocomplete="new-password" placeholder="Use a strong password"><button id="profileCreate">Create profile</button><div id="profileCreateStatus" class="status muted"></div></section>`;
    main.appendChild(profileView);navButton=document.createElement('button');navButton.type='button';navButton.dataset.view='profile';navButton.textContent='Profile';document.querySelector('.aurora-nav').appendChild(navButton);
    navButton.onclick=()=>{document.querySelectorAll('.aurora-view').forEach(v=>v.classList.toggle('active',v===profileView));document.querySelectorAll('.aurora-nav button').forEach(b=>b.classList.toggle('active',b===navButton));$('aurora-view-title').textContent='PROFILE';$('aurora-context-status').textContent='Identity, authentication and provider access';history.replaceState(null,'','#profile');refreshProfile();};
    $('profileSave').onclick=saveProfile;$('profileSignIn').onclick=showGate;$('profileSignOut').onclick=()=>{window.signOut();showGate();};$('profileSaveOpenRouter').onclick=()=>saveCredential('openrouter','primary',$('profileOpenRouterKey').value.trim());$('profileConnectPuter').onclick=async()=>{try{await window.connectPuter();$('profilePuterStatus').textContent='Puter account connected.';}catch(e){$('profilePuterStatus').textContent=e.message||String(e);}};
    $('profileCreate').onclick=async()=>{try{const email=$('profile-create-email').value.trim(),password=$('profile-create-password').value;if(!email||password.length<6)throw new Error('Email and a password of at least 6 characters are required.');await signup(email,password);$('profileCreateStatus').textContent='Profile created. Sign in with the new account.';showGate();$('gateEmail').value=email;$('gatePassword').value=password;}catch(e){$('profileCreateStatus').textContent=e.message;}};
  }
  function addStyle(){const s=document.createElement('style');s.textContent=`#aurora-signin-gate{position:fixed;inset:0;z-index:10001;background:rgba(5,9,13,.96);display:flex;align-items:center;justify-content:center;padding:20px}.aurora-auth-card{width:min(520px,100%);background:#111821;border:1px solid #334252;border-radius:14px;padding:28px;box-shadow:0 20px 70px #0008}.aurora-auth-card h1{margin:6px 0 8px}.aurora-auth-card label{display:block;margin-top:12px}.aurora-auth-card input{margin:5px 0 4px}.aurora-test-note{margin-top:18px;padding:12px;border:1px dashed #334252;border-radius:8px;color:#aeb9c6;font-size:12px;line-height:1.55}.aurora-auth-card .row{margin-top:10px}`;document.head.appendChild(s);}
  function boot(){if(!document.querySelector('.aurora-shell'))return setTimeout(boot,30);addStyle();createProfileView();if(!signedIn())showGate();else refreshProfile();}
  boot();
})();
